# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title #pretty

# Setup
title:            Ville Reine
tagline:          'Blogue de 2 montréalais exilés à Toronto'
description:      'Blogue de 2 montréalais exilés à Toronto.'
url:              http://hyde.getpoole.com

author:
  name:           'Michel Billard'
  url:            https://twitter.com/gogosse

paginate:         5
