# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title #pretty

# Setup
title:            Ville Reine
tagline:          'Blogue de 2 montréalais exilés à Toronto'
description:      'Blogue de 2 montréalais exilés à Toronto.'
url:              http://www.villereine.ca

author:
  name:           'Michel Billard'
  url:            https://twitter.com/gogosse

social_medias:
  - url: "http://twitter.com/villereineca"
    slug: "twitter"
  - url: "http://facebook.com/villereine"
    slug: "facebook"
  - url: "http://instagram.com/villereine"
    slug: "instagram"
  - url: "http://youtube.com/user/villereine"
    slug: "youtube"

paginate:         5
